server:
  port: 18089

spring:
  config:
    activate:
      on-profile: develop
  devtools:


logging:
  level:
    root: INFO
    '[analytics.scheduler]': DEBUG
  charset:
    console: UTF-8
    file: UTF-8
