spring:
  profiles:
    active: develop
  main:
    web-application-type: SERVLET
  jmx:
    enabled: true

server:
  error:
    path: /error
    whitelabel:
      enabled: false
  undertow:
    no-request-timeout: 10000
    accesslog:
      dir: logs/accesslog/
      pattern: '[%I] %t %{i,X-Forwarded-For} %l %r %s %b "%{i,Referer}" "%{i,User-Agent}" "%{i,GO-Agent}" %T'
      rotate: true
      prefix: access_log.
      suffix: log
      enabled: true
    threads:
      io: 32
      worker: 4096
    preserve-path-on-forward: true
    direct-buffers: true
    always-set-keep-alive: false

logging:
  file:
    path: logs

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false
    ping:
      enabled: false
